-- Total Revenue
SELECT SUM(amount) AS total_revenue
FROM payments;

-- Revenue by Product
SELECT p.product_name,
      SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_name
ORDER BY revenue DESC;

-- Top customer by spend
SELECT c.name,
  SUM(p.amount) AS total_spent
  FROM customer c
  JOIN orders o ON c.customer_id = o.customer_id 
  JOIN payments p ON o.order_id = p.order_id 
  GROUP BY c.name 
  ORDER BY total_spent DESC; 

-- Best selling products  
SELECT p.product_name,
  SUM (oi.quantity) AS total_sold
  FROM order_items oi
  JOIN products p ON oi.products=p.product_id
  GROUP BY p.product_name
  ORDER BY total_sold DESC;
  
  -- Total orders per customers
  SELECT c.name , COUNT(o.order_id) AS total_orders
  FROM customer c
  JOIN orders o ON o.customer_id=c.customer_id
  GROUP BY c.name;
  
  -- Top selling products
SELECT p.product_name, SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC;
  
  -- Customer who spent the most money
  SELECT c.name , SUM(p.amount) AS total_spent
  FROM customer c
  JOIN orders o ON c.customer_id=o.customer_id
  JOIN payments p ON o.order_id=p.order_id
  GROUP BY c.name
  ORDER BY total_spent DESC;
  
  -- revenue generated by each product
 SELECT p.product_name,
SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_name
ORDER BY revenue DESC;
  
  
  
  
